### ISSUE TITLE
mongoose-time was deleted

### ISSUE THREAD

**Issue by jherreracsw** [samtheprogram/mongoose-time-range#1]
Hi @samtheprogram ,
the repo mongoose-time was deleted and is not possible to use it as a submodule in this repository.
Can you add the missing repo?

![image](https://user-images.githubusercontent.com/49407134/58843363-c0f33b80-8637-11e9-8631-862d45ecd624.png)

**Comment by sammoore** [comment]
Hi @jherreracsw, I didn't realize anyone was using this, I'm happy to know you are! I'll keep a close eye on comments :) it's been moved, I will update the repo tonight when I get back.

Unfortunately I assume you have moved on since it's been a month since your comment. However, I should warn you if you still intend to use the library, I haven't updated it since the latest major version of `mongoose` was released, so it probably won't be compatible unless you use the same version of mongoose as specified in the package.json.

**Comment by sammoore** [comment]
The repository should now be available. Sorry for the inconvenience.
